name       : perl-digest-md5
version    : 2.55
release    : 2
source     :
    - https://cpan.metacpan.org/authors/id/G/GA/GAAS/Digest-MD5-2.55.tar.gz : 03b198a2d14425d951e5e50a885d3818c3162c8fe4c21e18d7798a9a179d0e3c
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Digest::MD5 - Perl interface to the MD5 Algorithm
description: |
    Digest::MD5 - Perl interface to the MD5 Algorithm
builddeps  :
    - perl
rundeps    :
    - perl
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
