name       : perl-digest-md5
version    : '2.58'
release    : 3
source     :
    - https://cpan.metacpan.org/authors/id/T/TO/TODDR/Digest-MD5-2.58.tar.gz : 7d0201977a76ad390a7fbcce1f159278599dcb34de123246bea0c6338dd7f714
homepage   : https://metacpan.org/pod/Digest::MD5
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Digest::MD5 - Perl interface to the MD5 Algorithm
description: |
    The Digest::MD5 module allows you to use the RSA Data Security Inc. MD5 Message Digest algorithm from within Perl programs. The algorithm takes as input a message of arbitrary length and produces as output a 128-bit "fingerprint" or "message digest" of the input.
builddeps  :
    - perl
rundeps    :
    - perl
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
